# Generated by Django 5.0.4 on 2025-06-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_remove_userprofile_interests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='interests',
        ),
    ]
